# Generated by Django 4.2.6 on 2023-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='keterangan',
            field=models.CharField(default='', max_length=255),
        ),
    ]
