# Generated by Django 4.2.6 on 2023-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_wishlist', '0002_wishlistitem_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
