# Generated by Django 4.2.5 on 2023-12-09 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("add_member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorit",
            fields=[
                ("title", models.TextField(blank=True, null=True)),
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("author", models.TextField(blank=True, null=True)),
                ("number_of_pages", models.IntegerField(blank=True, null=True)),
                ("date_published", models.TextField(blank=True, null=True)),
                ("publisher", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=100)),
                (
                    "tanggal_lahir",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
