# Generated by Django 4.2.6 on 2023-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam_buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='lama_peminjaman',
            field=models.IntegerField(default=1),
        ),
    ]
