# Generated by Django 5.0 on 2023-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam_buku', '0002_remove_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='lama_peminjaman',
            field=models.IntegerField(default=1),
        ),
    ]
